### PR TITLE
apply flake8 linting

### PR DESCRIPTION
**Pull request by gadfort**

### CODE REVIEW

**Review by volkamir — COMMENTED** [review]
The changes look ok but for some reason the tests now fail. Has anything changed in the version or run mode of the tools?

**Comment by gadfort** [comment]
@volkamir it was a parameter that was not used that I removed, but was still getting passed into the testbench. It should be fixed.

**Comment by volkamir** [comment]
The split parameter is actually needed since it is a parameter of the flex fifo. Anyway, let's merge now and see how to bring it. 
I am still not clear on why it failed since it was there before and never caused an issue.

**Review by volkamir — APPROVED** [review]
Approving without the split parameter. Will need to add it back.

**Comment by gadfort** [comment]
@volkamir I would suggest adding them back with needed functionality. As it was, it wasn't used by anything.

**Pull request merged**
